### ISSUE TITLE
Mise en retenue d'un élève depuis la liste des retenues

### ISSUE THREAD

**Issue by doc212** [doc212/ades#114]
Sur la page de la liste des retenues d'un type donné, pour chaque retenue, ajouter un bouton qui permet d'ajouter un élève à la retenue

![selection_005](https://cloud.githubusercontent.com/assets/2139164/8047600/ec52c8e8-0e47-11e5-9376-18bb3670bbd7.png)

De même sur la page qui liste les élèves pour une retenue donnée
![selection_007](https://cloud.githubusercontent.com/assets/2139164/8047651/6ca9f5f2-0e48-11e5-8122-f6f5a87b4d34.png)

**Comment by doc212** [comment]
Il faudrait approuver #76 rapidement car ça bloque le dev de cette fonctionnalité.
En effet, pour pouvoir créer une retenue sans d'abord choisir un élève, il faut pouvoir sélectionner le ou les élèves à mettre en retenue à partir de la page de création de la retenue

![selection_009](https://cloud.githubusercontent.com/assets/2139164/8067083/aeaa8842-0eeb-11e5-95aa-a5bf70d7845b.png)

**Comment by mprn17** [comment]
pour moi c'est ok .


Date: Tue, 9 Jun 2015 12:10:44 -0700

**Comment by mprn17** [comment]
Il faut séparer le bouton éditer du bouton ajouter et les mettre chacun dans leur colonne.

|Editer|Ajouter un élève|
| img  | img |
