### ISSUE TITLE
Signature de chaque évènement sur les fiche élèves

### ISSUE THREAD

**Issue by mprn17** [doc212/ades#65]
Il est indispensable que chaque évènement soit signé, marqué par le log de la personne qui l'encode.
En cas d'utilisateurs multiples, on voit tout de suite qui a encodé quoi.

**Comment by doc212** [comment]
Est-ce qu'il faut voir ça dans le tableau de synthèse aussi ?
![selection_003](https://cloud.githubusercontent.com/assets/2139164/8024653/98b16004-0d3a-11e5-8439-54dd555b64ac.png)

**Comment by mprn17** [comment]
Yep, oui c'est mieux 😉Date: Sun, 7 Jun 2015 08:28:40 -0700
