### ISSUE TITLE
Création/édition d'un fait pour plusieurs élèves en même temps

### ISSUE THREAD

**Issue by mprn17** [doc212/ades#76]
Il faut réfléchir à un moyen de sélectionner plusieurs élèves pour leur appliquer la même retenue.

**Comment by mprn17** [comment]
A partir de l'écran Retenues -> Liste

**Comment by doc212** [comment]
@mprn17 j'ai mis en ligne sur http://dev.educ-action.be une version qui permet de dupliquer un fait à d'autres élèves, soit au moment de la création du fait, soit par après en éditant le fait.

Est-ce que tu pourrais regarder et me dire ce que t'en penses ?

En particulier:
* est-ce que tous les faits doivent être duplicable ?
* est-ce qu'il faudrait ajouter un petit popup d'aide qui explique comment ça marche ou est-ce assez intuitif
* est-ce que le look n feel te va?

Moi de mon côté je vais déjà travailler sur un bouton qui permet de mettre un élève en retenue en partant de la liste des retenues: pour l'instant, on est obligé de retrouver la fiche de l'élève pour le mettre en retenue

**Comment by mprn17** [comment]
Hello,

Je trouve ça très bien et très pratique.
Pour le look, on peut améliorer mais j'ai pas trop d'idée. Sinon, je n'ai pas bien compris le système de filtres !😢
On peut considérer tous les faits potentiellement duplicables .

Très bonne idée pour la retenue .

On avait bossé sur un système de labellisation. Je ne retrouve plus le truc. Tu peux me dire quoi 😉 !

Bonne journée,

Mike


Date: Sat, 6 Jun 2015 12:03:42 -0700

**Comment by doc212** [comment]
> A partir de l'écran Retenues -> Liste

Voir #121

**Comment by mprn17** [comment]
* Ajouter une petite image pour indiquer qu'on peut effacer un élève + tooltip overlib
* Filtre par nom et/ou par classe : en faire un titre avec bg jaune.
* ajouter un cadre autour de la liste des élèves sélectionnés + bg light blue
